---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-studio-web-page
spec:
  selector:
    matchLabels:
      app: training-studio-web-page
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: training-studio-web-page
    spec:
      containers:
      - name: training-studio-web-page
        image: santoshnrao/demo-training-studio:28
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: training-studio-web-page
spec:
  selector:
    app: training-studio-web-page
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  training-studio-web-page
spec:
  prefix: /
  service: training-studio-web-page:80
  host: k8s.sndevops.xyz