apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  {{ include "demo-training-studio.fullname" . }}
  labels:
    {{- include "demo-training-studio.labels" . | nindent 4 }}
spec:
  prefix: "{{.Values.routing.path}}"
  service: {{ include "demo-training-studio.fullname" . }}:{{ .Values.service.port}}
  host: "{{.Values.routing.host}}"
